config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users, 
             :controllers => {
                               :sessions => 'api/sessions', 
                               :registrations => 'api/registrations'
                             }

  resources :users

  devise_scope :user do
    get "api/all", to: "api/registrations#index"
    authenticated :user do
      root :to => 'home#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'api/sessions#new', as: :unauthenticated_root
    end

    
  end

  post "users/save" =>"users#create"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable #:recoverable, :rememberable #, #:trackable, :validatable #, :lockable

  # Setup accessible (or protected) attributes for your model
  #attr_accessible :email, :password

  #devise :encryptable, :encryptor => :md5

  

#  def valid_password?(password)
 # 	return false if encrypted_password.blank?
  #	Devise.secure_compare(Devise::Encryptable::Encryptors::Md5.digest(password, nil, nil, nil), self.encrypted_password)
 # end

	#def role?(role)
	 #   return !!self.user.find_by_profile(profile.to_i)
	#end

	def admin?
	  self.profile == "admin"
	end

	def username?
	  self.profile == "username"
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      #sign_in(@user)
       redirect_to '/'
    else
       redirect_to '/'
    end
  end


  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    #puts YAML::dump(params)
    if @user.update_attributes(user_params)
      #redirect_to users_path, :notice => "User updated."
      return render :json => {:success => true, :update => true} 

    else
      return render :json => {:success => false} 
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

   def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :profile)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div align="left" class="col-md-9">
      <h2>Liistado de Usuarios</h2>  
    </div>
    <div class="col-md-3">
      <h3><%= link_to('Nuevo Usuario', new_user_path ) %></h3>
    </div>    
  </div>          
  <table class="table">
    <thead>
      <tr>
        <th>id</th>
        <th>Email</th>
        <th>Profile</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
            <td><%= user.id %></td>
            <td><%= user.email %></td>
            <td><%= user.profile %></td>
            <td>
              <%= link_to('Editar', user_path(user) ) %>
              <%= link_to("Eliminar", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') %>
            </td>
        </tr>
      <% end %> 
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<%#= form_for(@user, :url => users_path(@user)) do |f| %>
  <%#= devise_error_messages! %>

<%= form_for("user", :url => users_path,  html: { :id => "newUser", :class => "span3" }, :remote => true, :format => :json) do |f| %>

    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
          <h1 class="text-center login-title">REGISTAR USUARIO</h1>

          <div><%= f.label :email %><br />
          <%= f.email_field :email, :class => 'form-control' %></div>

          <div><%= f.label :password %><br />
          <%= f.password_field :password, :class => 'form-control' %></div>

          <div><%= f.label :password_confirmation %><br />
          <%= f.password_field :password_confirmation, :class => 'form-control' %></div>

          <div><%= f.label :profile %><br />
          <%= f.password_field :profile, :class => 'form-control' %></div>
          
          <%= button_tag 'Guardar', type: 'button', id: 'save', class: 'btn btn-lg btn-primary btn-block' %>
          <div><%= f.submit "Guardar" %></div>
        
        </div>
      </div>
    </div>
<% end %>

<%= javascript_include_tag "tin_usuarios" %>


<%#= render "devise/shared/links" %>

app/views/users/show.html.erb
<!--<h2>Edit <%#= resource_name.to_s.humanize %></h2>-->


<%#= form_for("user", :url => user_session_path, :html => {:id => "sign_in", :class => "span3"}, :remote => true, :format => :json) do |f| %>

<%= form_for("user", html: { :id => "updateUser", :class => "span3" }, :remote => true, :format => :json) do |f| %>

  <%#= devise_error_messages! %>
          
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
          <h1 class="text-center login-title">EDITAR USUARIO</h1>

              <%= f.label :email %>
              <%= f.email_field :email, :class => 'form-control', autofocus: true, :value => @user.email  %>
              <br>
              <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
              <%= f.password_field :password, :class => 'form-control', autocomplete: "off" %>
              <br>
              <%= f.label :password_confirmation %>
              <%= f.password_field :password_confirmation, :class => 'form-control', autocomplete: "off" %>
              <br>
              <%#= f.label :current_password %><!-- <i>(we need your current password to confirm your changes)</i><br />
              <%#= f.password_field :current_password, :class => 'form-control', autocomplete: "off" %>
              <br>-->
              <!--<div class="actions">
                <%#= f.submit "Update" %>
              </div>-->
              <%= button_tag 'UPDATE', type: 'button',class: 'btn btn-lg btn-primary btn-block update' %>
        </div>
      </div>
      <div class="row">
        <div align="center" class="col-sm-6 col-md-4 col-md-offset-4">
            <!--<h3 align="center">Cancelar mi Cuenta</h3>-->
            <br>
            <p><%#= button_to "Cancelar Cuenta", registration_path(resource_name), data: { confirm: "Seguro Desea Cancelar Cuenta" }, method: :delete %></p>

            <%= link_to "Atras", :back %>          
        </div>        
      </div>
    </div>
    <%= f.text_field :id, :value => @user.id  %>

<% end %>

<%= javascript_include_tag "tin_usuarios" %>