config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users, 
             :controllers => {
                               :sessions => 'api/sessions', 
                               :registrations => 'api/registrations'
                             }

  resources :users

  devise_scope :user do
    get "api/all", to: "api/registrations#index"
    authenticated :user do
      root :to => 'home#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'api/sessions#new', as: :unauthenticated_root
    end

    
  end

  post "users/save" =>"users#create"

end

app/views/layouts/_navegation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!--<div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>-->
    <ul class="nav navbar-nav">
      <li>
        <%= link_to('Inicio', authenticated_root_path ) %>
      </li>
      <li>
        <%= link_to('Editar Perfil', edit_user_registration_path ) %>
      </li>
      <li>
        <% if can? :manage, User %>
            <%= link_to('Administración', users_path ) %>
        <% end %>
      </li>
      <li>
          <a>Hola, <%= current_user.email %></a>
      </li>
      <li>
        <%= link_to('Cerrar Sesión', destroy_user_session_path, :method => :delete, :class => 'logout') %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!--<!DOCTYPE html>
<html>
<head>
  <title>Devise</title>
  <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%#= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
  <%= csrf_meta_tags %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
<body>

<%#= yield %>

</body>
</html>-->



<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Administracion de Usuarios</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%#= javascript_include_tag 'https://js.stripe.com/v2/' %>

    <%= csrf_meta_tags %>

  </head>
  <body>
        <% if user_signed_in? %>
          <%= render 'layouts/navegation' %>
        <% end %>

        <p class="alert-success"><%= notice %></p>
        <p class="alert-danger"><%= alert %></p>
        <%= yield %>

  </body>
</html>